insert into Terms(name, pronunciation, audio, source, description) values('apache', "ə'pætʃi", 'apache.mp3', "http://www.apache.org", 'Apache is a freely available Web server that is distributed under an "open source" license.');
insert into Terms(name, pronunciation, audio, source, description) values('maven', "'meiven", 'maven.mp3', "http://maven.apache.org", "Apache Maven is a software project management and comprehension tool. Maven can manage a project's build, reporting and documentation from a central piece of information.");
insert into Terms(name, pronunciation, audio, source, description) values('nginx', "'endʒin eks", 'nginx.mp3', "http://nginx.org", "nginx is an HTTP and reverse proxy server, as well as a mail proxy server, written by Igor Sysoev.");
insert into Terms(name, pronunciation, audio, source, description) values('java', "'dʒɑ:və", 'java.mp3', "http://www.java.com", "Java is a programming language originally developed by James Gosling at Sun Microsystems and released in 1995 as a core component of Sun Microsystems' Java platform.");
insert into Terms(name, pronunciation, audio, source, description) values('parameter', "pə'ræmitə", 'parameter.mp3', "", "In computer programming, a parameter is a special kind of variable, used in a subroutine to refer to one of the pieces of data provided as input to the subroutine.");			
insert into Terms(name, pronunciation, audio, source, description) values('cache', "kæʃ", 'cache.mp3', "", "In computer engineering, a cache is a component that transparently stores data so that future requests for that data can be served faster.");
insert into Terms(name, pronunciation, audio, source, description) values('c#', "si: ʃɑ:p", 'c#.mp3', "http://msdn.microsoft.com/en-us/vstudio/hh388566.aspx", "C# is a multi-paradigm programming language encompassing strong typing, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines.");
insert into Terms(name, pronunciation, audio, source, description) values('pixel', "'piksəl", 'pixel.mp3', "", "In digital imaging, a pixel is a single point in a raster image, or the smallest addressable screen element in a display device. It is the smallest unit of picture that can be represented or controlled.");
insert into Terms(name, pronunciation, audio, source, description) values('mockito', "mɔkitɔ", 'mockito.mp3', "http://code.google.com/p/mockito", 'Mockito is an open source testing framework for Java released under the MIT License. The framework allows the creation of Test Double objects called, "Mock Objects" in automated unit tests.');
insert into Terms(name, pronunciation, audio, source, description) values('firefox', "faiefɔ:ks", 'firefox.mp3', "http://www.mozilla.org", "Mozilla Firefox is a free and open source web browser descended from the Mozilla Application Suite and managed by Mozilla Corporation.");
insert into Terms(name, pronunciation, audio, source, description) values('chrome', "krəum", 'chrome.mp3', "http://www.google.cn/chrome", "Google Chrome is a web browser developed by Google that uses the WebKit layout engine. Google Chrome OS is a Linux-based operating system designed by Google to work exclusively with web applications.");
insert into Terms(name, pronunciation, audio, source, description) values('applet', "æplət", 'applet.mp3', "", "In computing, an applet is any small application that performs one specific task that runs within the scope of a larger program, often as a plug-in.");
insert into Terms(name, pronunciation, audio, source, description) values('agile', "'ædʒail, 'ædʒəl", 'agile.mp3', "", "Agile is a group of software development methodologies based on iterative and incremental development, where requirements and solutions evolve through collaboration between self-organizing, cross-functional teams.");
insert into Terms(name, pronunciation, audio, source, description) values('iteration', ".itə'reiʃən", 'iteration.mp3', "", "Iteration in computing is the repetition of a process within a computer program.");
insert into Terms(name, pronunciation, audio, source, description) values('linux', "'linəks, 'linʊks", 'linux.mp3', "https://www.linux.com", "Linux is a Unix-like computer operating system assembled under the model of free and open source software development and distribution.");
insert into Terms(name, pronunciation, audio, source, description) values('ubuntu', "ʊ:bʊ:ntʊ:", 'ubuntu.mp3', "http://www.ubuntu.com", "Ubuntu is a computer operating system based on the Debian Linux distribution and distributed as free and open source software, using its own desktop environment.");
								