CREATE TABLE WrongReadings(
	id INTEGER, 
	READING VARCHAR(50) not null, 
	TERM INTEGER, 
	COUNT INTEGER DEFAULT 0, 
	created_at timestamp, 
	updated_at timestamp, 
	CONSTRAINT PK_WRONGREADINGS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_WRONGREADINGS_TERM FOREIGN KEY(TERM) REFERENCES TERMS(ID)
);
