CREATE TABLE IPSTERMS(
	id INTEGER, 
	ip varchar(15) NOT NULL,
	term INTEGER NOT NULL,
	CONSTRAINT PK_IPS_TERMS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_TERMS_ID FOREIGN KEY(term) REFERENCES TERMS(ID),
	CONSTRAINT UN_IP_TERM UNIQUE (ip,term)
);