CREATE TABLE IPSTERMS(
	id INTEGER, 
	ip varchar(15) NOT NULL,
	term INTEGER NOT NULL,
	reading INTEGER NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP, 
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_IPS_TERMS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_VOTES_TERMS_ID FOREIGN KEY(term) REFERENCES TERMS(ID), 
	CONSTRAINT FK_VOTES_READINGS_ID FOREIGN KEY(reading) REFERENCES PRONUNCIATIONS(ID)
);