CREATE TABLE WRONG_PRONUNCIATIONS(
	id INTEGER,  
	pronunciation varchar(50) NOT NULL,
	audio varchar(50),
	count INTEGER default 0,
	term INTEGER NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP, 
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_WRONG_PRONUNCIATIONS_ID PRIMARY KEY(ID),
	CONSTRAINT FK_TERMS_ID FOREIGN KEY(term) REFERENCES TERMS(ID)
);