CREATE TABLE VOTES(
	id INTEGER, 
	userId varchar(15) NOT NULL,
	term INTEGER NOT NULL,
	reading INTEGER NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP, 
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_VOTES_ID PRIMARY KEY(ID),
	CONSTRAINT FK_VOTES_TERMS_ID FOREIGN KEY(term) REFERENCES TERMS(ID), 
	CONSTRAINT FK_VOTES_READINGS_ID FOREIGN KEY(reading) REFERENCES PRONUNCIATIONS(ID), 
	CONSTRAINT FK_VOTES_USERS_ID FOREIGN KEY(userId) REFERENCES USERS(ID)
);